"""adding med info

Revision ID: 9991d3786b52
Revises: b9dd450ac53b
Create Date: 2023-07-30 00:02:55.136768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9991d3786b52'
down_revision = 'b9dd450ac53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med',
    sa.Column('med_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('med_name', sa.String(length=500), nullable=True),
    sa.Column('time_needed', sa.String(length=100), nullable=True),
    sa.Column('last_taken', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('med_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med')
    # ### end Alembic commands ###
