"""initial migration

Revision ID: dda3ac06f008
Revises: 
Create Date: 2023-08-06 18:00:08.961481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda3ac06f008'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('birthday', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('goal_weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('est_water_intake', sa.Float(), nullable=True),
    sa.Column('est_base_calories', sa.Integer(), nullable=True),
    sa.Column('est_goal_calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('food',
    sa.Column('food_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_name', sa.String(length=500), nullable=True),
    sa.Column('meal', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.String(length=500), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('food_id')
    )
    op.create_table('med',
    sa.Column('med_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('med_name', sa.String(length=500), nullable=True),
    sa.Column('time_needed', sa.String(length=100), nullable=True),
    sa.Column('last_taken', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('med_id')
    )
    op.create_table('saved_exercise',
    sa.Column('saved_exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('calories_per_hour', sa.Float(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('saved_exercise_id')
    )
    op.create_table('saved_recipe',
    sa.Column('saved_recipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('ingredients', sa.Text(length=10000), nullable=True),
    sa.Column('servings', sa.String(length=500), nullable=True),
    sa.Column('instructions', sa.Text(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('saved_recipe_id')
    )
    op.create_table('water',
    sa.Column('water_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('water_id')
    )
    op.create_table('weight',
    sa.Column('weight_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight_in_lbs', sa.Float(), nullable=True),
    sa.Column('weight_in_kg', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('weight_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight')
    op.drop_table('water')
    op.drop_table('saved_recipe')
    op.drop_table('saved_exercise')
    op.drop_table('med')
    op.drop_table('food')
    op.drop_table('exercise')
    op.drop_table('user')
    # ### end Alembic commands ###
